version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./dataMongoDB:/data
    networks:
      - challenge-network

  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app
    command: ./gradlew bootRun
    networks:
      - challenge-network
    depends_on:
      - mongo
      
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge